import React from "react"

function Header() {
  return (
    <header>
        <title>David Moon</title>
        <meta name="description" content="Generated by Gatsby app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../images/favicon.png" />
    </header>
  )
}

export default Header